### ISSUE TITLE
Firebase admin with iOS app

### ISSUE THREAD

**Issue by AdieOlami** [raynstudios/firebase-admin-dashboard#1]
Great work. I have a project in iOS and would like to have an admin area for this project. would this library work with it? I would really appritiate a response. There are fields already in my Firestore. so I would like to know. Thanks

**Comment by rajat1saxena** [comment]
Thank you. This project can serve as a starter project for building an admin dashboard for your app but it has some limitations like the sessions expire upon page reload.
