### ISSUE TITLE
Error when I run yarn run passwdgen <username> <password>

### ISSUE THREAD

**Issue by AdieOlami** [raynstudios/firebase-admin-dashboard#2]
module.js:471
    throw err;
    ^

Error: Cannot find module 'bcryptjs'
    at Function.Module._resolveFilename (module.js:469:15)
    at Function.Module._load (module.js:417:25)

**Comment by rajat1saxena** [comment]
You need bcryptjs to be globally installed. I will probably fix this in the next iteration. For now just install it globally using:
```
npm i -g bcrypt
```
