### ISSUE TITLE
Where do I find "your secret"?

### ISSUE THREAD

**Issue by willvlad** [raynstudios/firebase-admin-dashboard#3]
Where do we get this secret from?

firebase functions:config:set auth.secret="<YOUR_SECRET>"

**Comment by rajat1saxena** [comment]
It is just a random string which you can select (or create) on your own. Nothing special here.

**Comment by roeniss** [comment]
> It is just a random string which you can select (or create) on your own. Nothing special here.

I think this comment should be on readme.
